# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Command-line interface for SecretHub"
  homepage "https://secrethub.io"
  url "https://github.com/secrethub/secrethub-cli/releases/download/v0.20.0/secrethub-v0.20.0-darwin-amd64.tar.gz"
  version "0.20.0"
  sha256 "47e9d8ce2478612d72914cd8a2b3273df11c951795878007f00d27867e4b842b"

  def install
    bin.install "bin/{{ .ProjectName }}"
  end
end
