# This file was generated by GoReleaser. DO NOT EDIT.
class SecrethubCli < Formula
  desc "Command-line interface for SecretHub"
  homepage "https://secrethub.io"
  url "https://github.com/secrethub/secrethub-cli/releases/download/v0.21.0/secrethub-v0.21.0-darwin-amd64.tar.gz"
  version "0.21.0"
  sha256 "a82774ddc40d2b1c5201e98c0322d0b302c674dd7f3ae26beb1f1fd5e5579277"

  def install
    bin.install "bin/secrethub"
  end
end
